config/routes.rb
Rails.application.routes.draw do
  root :to => "tickets#index"
  resources :tickets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  #-----------------backend validations--------------------------
  validates_presence_of :title, :notes

  #-----------scope for finding ticket for today-----------------------
  scope :today_tickets, -> { where("created_at >= ?", Time.zone.now.beginning_of_day) }

  #--------use of callbacks-----------------------------------
  after_create do             #assigning uniq ticket number
    number = Time.now.strftime("%Y-%d-%m")+"-"+self.class.last_ticket_number  #calling class method for uniq incremented number from db
    self.update_attributes(:number => number)
  end

  #--------------class method--------------------------------
  def self.last_ticket_number    #method to find uniq ticket number for the day
    last_number = today_tickets.last&.number
    last_number ? last_number.split("-").last + 1 : "1"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  #callbacks for controller
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all.reverse_order   #retriving record as LIFO queue
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :number, :due_date, :phone_number, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaCodingTest</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

<!-- importing local assets -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- importing cdn assets -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>

<body>

<!-- importing header -->
<%= render "layouts/partials/header" %>

<div class="container mt-4">
  <%= yield %>
</div>
<!-- importing footer -->
<%= render "layouts/partials/footer" %>
</body>
</html>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>

  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>

      <% ticket.errors.full_messages.each do |message| %>
          <div class="alert alert-danger" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      <% end %>

      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Title</label>
      <%= form.text_field 'title', class:"form-control", id:"inputEmail4", placeholder:"Title" %>
    </div>

    <div class="form-group col-md-6">
      <label for="due_date">Due Date</label>
      <div class="datepicker date input-group p-0 shadow-sm">
          <%= form.text_field 'due_date', placeholder:"Choose a due date", class:"form-control ", id:"due_date"%>
          <div class="input-group-append"><span class="input-group-text px-4"><i class="fa fa-clock-o"></i></span></div>
        </div>
    </div>
  </div>

  <div class="form-group">
    <label for="notes">Title</label>
    <%= form.text_area 'notes', rows: 5, class:"form-control", id:"notes", placeholder:"Title" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>

<% end %>

app/views/tickets/_notice.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
  <p id="notice"><%= notice %></p>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<%= render 'tickets/notice', notice: notice %>

<div>
    <h1 class="float-left">Tickets</h1>
    <%= link_to 'New Ticket', new_ticket_path, class: "float-right btn btn-primary " %>
</div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Title</th>
    <th>Number</th>
    <th>Due Date</th>
    <th colspan="3">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.title.humanize %></td>
      <td><%= ticket.number %></td>
      <td><%= ticket.due_date %></td>
      <td><%= link_to 'Show', ticket, class: "btn btn-primary" %></td>
      <td><%= link_to 'Edit', edit_ticket_path(ticket), class: " btn btn-info" %></td>
      <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<div class="mt-5">
  <h1>New Ticket</h1>
  <%= render 'form', ticket: @ticket %>

  <%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/show.html.erb
<%= render 'tickets/notice', notice: notice %>

<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th>Title</th>
    <th>Number</th>
    <th>Due Date</th>
  </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @ticket.title.humanize %></td>
      <td><%= @ticket.number %></td>
      <td><%= @ticket.due_date %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>